pipeline {
    agent any
    
    tools {
        maven 'maven-3.9.5'
    }

    stages {
        stage ('BUILD') {
            steps {
                sh '''
                  cd ./maven/simple-war
                  mvn clean package
                  cd ./target
                  ls
                '''
            }
        }
        stage ('DEPLOY-TOMCAT') {
            steps {
                script {
                    deploy adapters: [tomcat9(credentialsId: 'tomcat-cred', path: '', 
                    url: 'http://13.126.203.164:8080')], contextPath: '/itdefined-war-1.0.0', 
                    war: 'maven/simple-war/target/itdefined-war-1.0.0.war'
                }
            }
        }
    }
}