apiVersion: v1 
kind: Pod 
metadata:
  name: pod-conf-secret 
spec: 
  containers:
  - name: nginx 
    image: nginx 
    ports:
      - containerPort: 80 
    volumeMounts: 
    - name: config-vol
      mountPath: "/apps/conf-vol"
    - name: secret-vol 
      mountPath: "/apps/secret-vol"
  volumes:
  - name: config-vol
    configMap:
      name: my-practice-configmap
  - name: secret-vol
    secret:
      secretName: my-secret-practice 