#practing docker compose file for prometheus, alertmanager, grafana, node-exporter
version: '3.8'
volumes: 
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    restart: always 
    ports:
      - 9090:9090
    volumes: 
    commands:
  node-exporter:
    image: prom/node-exporter 
    restart: always 
    ports:
      - 9100:9100
    volumes:
    commands:
  alertmanager:
    image: prom/alertmanager 
    restart: always 
    ports:
      - 9093:9093
    commands:
    volumes:
  grafana:
    image: grafana/grafana 
    ports: 
      - 3000:3000
    
# dockerfile for java application
--- 
FROM openjdk:11-jre-slim 
WORKDIR /app
COPY target/<your-jar-file>.jar .
ENTRYPOINT ['java', '-jar', '<your-jar-file>.jar'] 


