apiVersion: v1
kind: Pod
metadata:
  name: pod-sct-vol
spec:
  containers:
    - name: nginx-sct
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: my-sct-vol
      