apiVersion: v1 
kind: Pod 
metadata:
  name: resource-pod 
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80 
    resources:
      requests:
        memory: "64Mi" 
        cpu: "500m"  
      limits:
        memory: "128Mi" 
        cpu: "1000m" 