apiVersion: apps/v1
kind: Deamonset
metadata:
  name: ip-app-deamonset-pract
  labels:
    name: deamonset-practice
spec: 
  selector:
    matchLabels:
      app: ip-app-deamonset
  template:
    metadata:
      labels:
        app: ip-app-deamonset
    spec:
      containers:
      - name: ip-app-deamonset-pod
        image: chandrunaikdevops/new-ip-app:2
        ports:
          - containerPort: 8080