apiVersion: v1 
kind: Pod
metadata:
  name: empty-dir-pod
spec:
  containers:
  - name: nginx
    image: nginx 
    ports:
      - containerPort: 80 
    volumeMounts:
    - name: emptydir-vol
      mountPath: "/var/log/nginx"
  volumes:
  - name: emptydir-vol
    emptyDir: {}