apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler 
metadata:
  name: hpa-pod 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-hpa-php-app
  minReplicaes: 1
  maxReplicas: 10 
  metrics:
    - type: Resource 
      resources:
        name: cpu
        target: 
          type: Utilization 
          averageUtilization: 80