apiVersion: batch/v1
kind: Job
metadata:
  name: job-practice
spec:
  completions: 5
  parallelism: 2
  activeDeadlineSeconds: 10
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - /bin/sh
        - -c 
        - echo Practice Job; sleep 5;
