apiVersion: v1 
kind: Service
metadata:
  name: node-port-svc
spec:
  type: NodePort 
  selector:
    matchLabels:
      app: ip-app-deamonset
  ports: 
  - name: http
    port: 30002
    targetPort: 8080
    nodePort: 8090