apiVersion: v1 
kind: Pod 
metadata:
  name: pvc-pod 
spec:
  containers:
  - name: nginx 
    image: nginx 
    ports:
      - containerPort: 80 
    volumeMounts:
    - name: pvc-vol
      mountPath: "/apps/pvc_vol"
  volumes:
  - name: pvc-vol
    PersistentVolumeClaim: 
      claimName: my-pvc-practice 