apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ip-app-sfs-pract
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ip-app-sfs
  template:
    metadata:
      labels:
        app: ip-app-sfs
    spec:
      containers:
      - name: ip-app-sfs-image
        image: chandrunaikdevops/new-ip-app:2
        ports:
          - containerPort: 8080