apiVersion: v1
kind: Pod
metadata:
  name: pod-sct
spec:
  containers:
    - name: nginx-sct
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: my-sct
              key: db_user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-sct
              key: db_password