apiVersion: v1
kind: Pod
metadata:
  name: pod-cm
spec:
  containers:
    - name: nginx-cm
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: my-cm
              key: env
        - name: APP
          valueFrom:
            configMapKeyRef:
              name: my-cm
              key: app
