apiVersion: v1
kind: Pod
metadata:
  name: pod-empty-dir
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-vol
          mountPath: "/var/log/nginx"
    - name: busybox-empty
      image: busybox
      command: ["/bin/bash"]
      args: ["-c", "while true; do ls /var/log/nginx; cat /var/log/nginx/access.log; sleep 5; done"]
      volumeMounts:
        - name: shared-vol
          mountPath: "/var/log/nginx"
  volumes:
    - name: shared-vol
      emptyDir: {}