pipeline {
    agent {
       label 'slave1'
    } 
    stages {
        stage ('BUILD') {
            steps {
                sh 'sleep 2'
            }
        }
        stage ('TEST') {
            steps {
                sh 'sleep 3'
            }
        }
        stage ('DEPLOY') {
            steps {
               sh 'sleep 2' 
            }
        }
    }
}
