pipeline {
    agent any 
    stages {
        stage ('BUILD') {
            steps {
                sh 'sleep 2'
            }
        }
        stage ('TEST') {
            steps {
                sh 'sleep 2'
            }
        }
        stage ('DEPLOY') {
            steps {
               sh 'sleep 2' 
            }
        }
    }
}
