apiVersion: v1
kind: Pod
metadata: 
  name: init-container
spec:
  initContainers:
    - name: init-busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 20"]
  containers:
    - name: nginx-app
      image: nginx
      ports:
        - containerPort: 80