apiVersion: v1
kind: Pod
metadata: 
  name: side-car-container
spec:
  containers:
    - name: side-car-nginx
      image: nginx
      ports: 
        - containerPort: 80
    - name: side-car-busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 1000"]