apiVersion: v1
kind: Service 
metadata: 
    name: my-headless-svc
spec:
    clusterIP: None     
    selector:
        app: ip-app-sfs
    ports: 
      - name: http 
        port: 30001
        targetPort: 8080