apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 1
  # parallelism: 5
  # backoffLimit: 2
  activeDeadlineSeconds: 5
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
          - /bin/sh
          - -c
          - "sleep 10; exit"
      restartPolicy: Never