apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-select-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec: 
      nodeSelector:
        env: dev      
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80