apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-select-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec: 
      tolerations:
        - key:  test
          #value: podEnv
          effect: NoSchedule
          #operator: "Equal"
          operator: "Exists" 
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80