apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata:
  name: my-new-role
  namespace: default 
rules:
- apiGroups: []
  resources: ['pod', 'services', 'deployment']
  verbs: ['get', 'list']