apiVersion: v1 
kind: Pod
metadata:
  name: init-pod-container
spec:
  initContainers:
  - name: busybox-init
    image: busybox 
    command: ["/bin/sh"]
    args: ["-c", "sleep 20"]
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80