apiVersion: v1
kind: Pod 
metadata:
  name: side-car-pod 
spec: 
  containers:
  - name: nginx 
    image: nginx 
    ports:
      - containerPort: 80 
  - name: busybox 
    image: busybox
    command: 
    - bin/sh 
    - -c 
    - "sleep 10"