apiVersion: v1 
kind: Pod 
metadata:
  name: pod-conf-secret
spec:
  containers:
  - name: nginx 
    image: nginx 
    ports: 
      - containerPort: 80 
    env:
    - name: ENV 
      valueFrom:
        configMapKeyRef:
          name: my-config 
          key: env
    - name: TEST 
      valueFrom:
        configMapKeyRef:
          name: my-config 
          key: test 
    - name: DB_USER 
      valueFrom:
        secretKeyRef:
          name: my-sct
          key: db_user 
    - name: DB_PASSWD
      valueFrom:
        secretKeyRef:
          name: my-sct
          key: db_passwd