apiVersion: v1
kind: Pod
metadata: 
  name: side-car-container
spec:
  containers:
    - name: ip-app-container
      image: chandrunaikdevops/new-ip-app:2
      ports: 
        - containerPort: 8080
    - name: side-car-busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 1000"]